services:
  - type: web
    name: movie-recommender-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir gunicorn && pip install --no-cache-dir -r requirements.txt && python cache_model.py && python reduce_dataset.py && python main.py
    startCommand: gunicorn flask_api:app --bind 0.0.0.0:$PORT --timeout 600 --workers 1 --threads 1 --worker-class sync --max-requests 100 --max-requests-jitter 10
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: PORT
        sync: false
