services:
  - type: web
    name: movie-recommender-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir gunicorn && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn flask_api:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: PORT
        sync: false
